// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>


const char THING_ID[] = "bf5c9ec3-13da-475a-a1f1-bd5b53e16a78";

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_PASS;    // Network password (use for WPA, or use as key for WEP)


CloudCounter drinkCount;
CloudCounter fillCount;
CloudVolume consumption;
CloudVolume consumptionTotal;
CloudLength distance;

void initProperties(){

  ArduinoCloud.setThingId(THING_ID);
  ArduinoCloud.addProperty(drinkCount, READ, 1 * SECONDS, NULL);
  ArduinoCloud.addProperty(fillCount, READ, 1 * SECONDS, NULL);
  ArduinoCloud.addProperty(consumption, READ, 1 * SECONDS, NULL);
  ArduinoCloud.addProperty(consumptionTotal, READ, 1 * SECONDS, NULL);
  ArduinoCloud.addProperty(distance, READ, 1 * SECONDS, NULL);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
